version: '3.8'

services:
  app:
    build: .
  nginx:
    image: nginx:latest
    container_name: nginx_proxy_container
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      # This line mounts ONLY your site config file
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      # This line mounts ONLY your certs folder
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - app